# ADD github_username, github_password to drone's secret!!
pipeline:
  test:
    image: asia.gcr.io/develop-156705/dmd:${D_VERSION}
    commands:
      - dub test --compiler=${COMPILER}

  doc:
    image: asia.gcr.io/develop-156705/dmd:${D_VERSION}
    commands:
      - echo machine github.com >> ~/.netrc
      - echo login $GITHUB_USERNAME >> ~/.netrc
      - echo password $GITHUB_PASSWORD >> ~/.netrc
      - git config --global user.email "yosupo06@gmail.com"
      - git config --global user.name "Kohei Morita"
      - git subtree pull --prefix docs/ origin gh-pages -m 'Merge branch'
      - dub run dunkelheit:document
      - git add -A
      - git commit --allow-empty -m 'make documents'
      - git subtree push --prefix docs/ origin gh-pages
    secrets: [github_username, github_password]
    when:
      branch: master
      matrix:
        D_VERSION: 2.076.0
        COMPILER: dmd

matrix:
  include:
    - D_VERSION: 2.076.0
      COMPILER: dmd
    - D_VERSION: 2.076.0
      COMPILER: dmd-x86

    - D_VERSION: 2.075.1
      COMPILER: dmd
    - D_VERSION: 2.075.1
      COMPILER: dmd-x86
    - D_VERSION: 2.075.0
      COMPILER: dmd
    - D_VERSION: 2.075.0
      COMPILER: dmd-x86

    - D_VERSION: 2.074.1
      COMPILER: dmd
    - D_VERSION: 2.074.1
      COMPILER: dmd-x86
    - D_VERSION: 2.074.0
      COMPILER: dmd
    - D_VERSION: 2.074.0
      COMPILER: dmd-x86

    - D_VERSION: 2.073.2
      COMPILER: dmd
    - D_VERSION: 2.073.0
      COMPILER: dmd

    - D_VERSION: 2.072.2
      COMPILER: dmd
    - D_VERSION: 2.072.0
      COMPILER: dmd
    
    - D_VERSION: 2.071.2
      COMPILER: dmd
    - D_VERSION: 2.071.0
      COMPILER: dmd

    - D_VERSION: 2.070.2
      COMPILER: dmd
    - D_VERSION: 2.070.1
      COMPILER: dmd
    - D_VERSION: 2.070.0
      COMPILER: dmd

